//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacionDetalle
    {
        public int IdCotizacion { get; set; }
        public int IdProducto { get; set; }
        public int IdMedida { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Unitario { get; set; }
        public decimal Precio { get; set; }
    
        public virtual cotizacion cotizacion { get; set; }
        public virtual medidas medidas { get; set; }
        public virtual productos productos { get; set; }
    }
}
