//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalles_salud
    {
        public int Id { get; set; }
        public Nullable<int> Id_salud { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
    }
}
