//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class distribuidores
    {
        public int Id { get; set; }
        public string No_cte { get; set; }
        public string Planta { get; set; }
        public string Nombre_fact { get; set; }
        public string Nombre_com { get; set; }
        public string Direccion { get; set; }
        public string Barrio { get; set; }
        public string C_P { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Mail { get; set; }
        public string Categoria { get; set; }
        public string Horario { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Mapa { get; set; }
    }
}
