//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaltaDBEntities : DbContext
    {
        public MaltaDBEntities()
            : base("name=MaltaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<detalles_producto> detalles_producto { get; set; }
        public virtual DbSet<especies> especies { get; set; }
        public virtual DbSet<marcas> marcas { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<lineas> lineas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<detalles_salud> detalles_salud { get; set; }
        public virtual DbSet<salud> salud { get; set; }
        public virtual DbSet<blog> blog { get; set; }
        public virtual DbSet<distribuidores> distribuidores { get; set; }
    }
}
