//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.detalles_producto = new HashSet<detalles_producto>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_linea { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
        public string Brochure { get; set; }
        public string Vademecum { get; set; }
        public string Video { get; set; }
        public string Params_dist { get; set; }
        public string Proteina { get; set; }
        public string Grasa { get; set; }
        public string Humedad { get; set; }
        public string Ceniza { get; set; }
        public string Eln { get; set; }
        public string Fibra { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Keyword { get; set; }
        public string Target { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalles_producto> detalles_producto { get; set; }
        public virtual productos productos1 { get; set; }
        public virtual productos productos2 { get; set; }
        public virtual lineas lineas { get; set; }
    }
}
