//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salud
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
        public string Tipo { get; set; }
        public string Indicaciones { get; set; }
        public string Contraindicaciones { get; set; }
        public string Administracion { get; set; }
        public string Interaccion { get; set; }
        public string Reacciones { get; set; }
        public string Uso { get; set; }
        public string Brochure { get; set; }
        public string Vademecum { get; set; }
        public string Video { get; set; }
        public string Params_dist { get; set; }
    }
}
